dist: xenial
language: python
cache: pip

python:
  - "3.7"
  - "3.8"

install:
  - git clone https://github.com/evennia/evennia.git ../evennia
  - pip install -e ../evennia

script:
  - evennia test --settings settings.py
